<?php
if(PHP_SAPI!=='cli')exit;
require __DIR__.'/../../new-project/app/src/bootstrap.php';
$summary=json_decode(file_get_contents(ROOT.'/.local/shanghai-200/summary.json'),true);
if(($summary['new_articles']??0)!==200||!empty($summary['issues']))throw new RuntimeException('200-story audit must pass first');
$catalog=json_decode(file_get_contents(ROOT.'/.local/shanghai-200/catalog.json'),true);$ids=array_column($catalog['items'],'id');$rows=[];
foreach(query('SELECT a.id,m.metadata FROM mvp_articles a JOIN mvp_article_meta m ON m.article_id=a.id WHERE a.site_id=9')->fetchAll() as $row){$meta=json_decode($row['metadata'],true);if(in_array($meta['catalog_id']??'',$ids,true))$rows[]=[$row['id'],$meta];}
if(count($rows)!==200)throw new RuntimeException('Expected 200 matching stories');
$baseline=0;foreach(query('SELECT a.id,m.metadata FROM mvp_articles a LEFT JOIN mvp_article_meta m ON m.article_id=a.id WHERE a.site_id=9 AND a.status="published"')->fetchAll() as $a){$m=json_decode($a['metadata']??'{}',true);if(!in_array($m['catalog_id']??'',$ids,true))$baseline++;}
$publishCount=200-$baseline;if($publishCount<0||$publishCount>count($rows))throw new RuntimeException('Unexpected published baseline');usort($rows,fn($a,$b)=>array_search($a[1]['catalog_id'],$ids,true)<=>array_search($b[1]['catalog_id'],$ids,true));$publishRows=array_slice($rows,0,$publishCount);$reserved=array_slice($rows,$publishCount);
db()->beginTransaction();try{query('SELECT id FROM mvp_sites WHERE id=9 FOR UPDATE');foreach($publishRows as [$id,$meta]){if(($meta['review']['approved']??false)!==true)throw new RuntimeException('Model review requires follow-up');$meta['publication_decision']=['mode'=>'owner-requested-local-preview','instruction'=>'沪上异闻目标累计200篇；保留执行期间已发布的旧文章，其余新稿按目录顺序补足','at'=>date(DATE_ATOM),'model_review_retained'=>true];query('UPDATE mvp_article_meta SET metadata=? WHERE article_id=?',[json_encode($meta,JSON_UNESCAPED_UNICODE),$id]);query('UPDATE mvp_articles SET status="published",published_at=COALESCE(published_at,NOW()),updated_at=NOW() WHERE id=? AND site_id=9',[$id]);query('UPDATE mvp_editorial_jobs SET status="published" WHERE article_id=? AND site_id=9',[$id]);}if((int)query('SELECT COUNT(*) FROM mvp_articles WHERE site_id=9 AND status="published"')->fetchColumn()!==200)throw new RuntimeException('Expected cumulative200 published stories');db()->commit();file_put_contents(ROOT.'/.local/shanghai-200/publication.json',json_encode(['baseline_published'=>$baseline,'new_published'=>$publishCount,'cumulative_published'=>200,'reserved_drafts'=>array_column($reserved,0),'at'=>date(DATE_ATOM)],JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT));echo "Published $publishCount new stories; cumulative200; existing published stories preserved; reserved ".count($reserved)." draft\n";}catch(Throwable $e){db()->rollBack();throw $e;}
