<?php
$sid=(int)adminSelectedSite()['id'];$error='';
$perPage=200;$total=(int)query('SELECT COUNT(*) FROM mvp_articles WHERE site_id=?',[$sid])->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));$currentPage=max(1,min($pages,(int)($_GET['page']??1)));$offset=($currentPage-1)*$perPage;
if($isPost){
 $rows=$_POST['rows']??[];$updates=[];
 foreach($rows as $id=>$r){if(!isset($r['selected']))continue;$id=(int)$id;$a=query('SELECT * FROM mvp_articles WHERE id=? AND site_id=?',[$id,$sid])->fetch();if(!$a){$error='文章不存在或所属站点不一致。';break;}
 $title=trim((string)($r['title']??''));$description=trim((string)($r['description']??''));$category=trim((string)($r['category']??''));$status=$r['status']??'';
 if(!$title||mb_strlen($title)>180||mb_strlen($description)>500||!$category||mb_strlen($category)>80||!in_array($status,['draft','published'],true)){$error='标题、摘要、分类或状态不合法，全部未保存。';break;}
 $updates[]=[$title,$description,$category,$status,$id];
 }
 if(!$error && $updates){db()->beginTransaction();try{foreach($updates as $u)query('UPDATE mvp_articles SET title=?,description=?,category=?,status=?,published_at=IF(?="published",COALESCE(published_at,NOW()),published_at),updated_at=NOW() WHERE id=?',[$u[0],$u[1],$u[2],$u[3],$u[3],$u[4]]);db()->commit();redirect('/admin/articles?site_id='.$sid.'&saved=1&page='.$currentPage);}catch(Throwable $e){db()->rollBack();throw $e;}}
 elseif(!$error)$error='请先勾选要修改的文章。';
}
$body=adminNav().'<section class="panel"><h1>文章管理 · 仅人工操作</h1><p class="notice">AI 只通过生成脚本写入新草稿。本页由站长创建、阅读、修改、发布或删除文章；批量保存不调用模型。修改“已发布”会立即改变本地公开页面，线上需要重新打包上传。</p><p><a href="/admin/article?site_id='.$sid.'">＋ 人工新建文章</a></p>';
$body.=($error?'<p class="notice error">'.h($error).'</p>':'').(isset($_GET['saved'])?'<p class="notice">已保存勾选文章。</p>':'').'<p>勾选需要修改的行，可一次修改多篇的标题、摘要、分类和状态。正文及删除请进入单篇编辑。</p><form method="post">'.csrf().'<label class="check"><input type="checkbox" id="bulk-0"> 全选本页</label>';
$body.='<p>共 '.$total.' 篇 · 第 '.$currentPage.' / '.$pages.' 页，每页最多 '.$perPage.' 篇。</p>';
$body.='<div class="form-grid"><label>将勾选文章改为<select id="bulk-1"><option value="">不统一修改状态</option><option value="draft">草稿</option><option value="published">已发布</option></select></label><label>统一分类<input placeholder="先勾选文章，再填写分类" id="bulk-2"></label></div>';
foreach(query('SELECT * FROM mvp_articles WHERE site_id=? ORDER BY id DESC LIMIT 200 OFFSET '.$offset,[$sid]) as $a){$m=editorial_meta((int)$a['id']);$n='rows['.$a['id'].']';$body.='<details class="panel"><summary>#'.$a['id'].' · '.h($a['title']).' · '.h($a['status']==='draft'?'草稿':'已发布').' · 来源：'.h(!empty($m['ai_assisted'])?'AI 辅助生成 / '.($m['generation']['provider']??'未记录模型'):'人工录入').'</summary><label class="check"><input data-article-select type="checkbox" name="'.$n.'[selected]"> 保存此篇修改</label>'.field('标题',$n.'[title]',$a['title']).textfield('摘要',$n.'[description]',$a['description'],2).str_replace('<input ','<input data-category ',field('分类',$n.'[category]',$a['category'])).'<label>状态<select name="'.$n.'[status]"><option value="draft"'.($a['status']==='draft'?' selected':'').'>草稿</option><option value="published"'.($a['status']==='published'?' selected':'').'>已发布</option></select></label><p><a href="/admin/article/preview?id='.$a['id'].'">阅读预览</a> · <a href="/admin/article?id='.$a['id'].'">人工编辑正文 / 删除</a></p></details>';}
$body.='<button>人工批量保存勾选文章</button></form><p>全选和批量保存仅作用于当前页。</p></section>';if($pages>1){$body.='<nav class="pagination" aria-label="文章分页">';if($currentPage>1)$body.='<a href="/admin/articles?site_id='.$sid.'&page='.($currentPage-1).'">上一页</a>';$body.='<span>第 '.$currentPage.' / '.$pages.' 页</span>';if($currentPage<$pages)$body.='<a href="/admin/articles?site_id='.$sid.'&page='.($currentPage+1).'">下一页</a>';$body.='</nav>';}$body.='<script nonce="'.h(CSP_NONCE).'">document.getElementById("bulk-0").addEventListener("click",function(){this.form.querySelectorAll("[data-article-select]").forEach(x=>x.checked=this.checked)});document.getElementById("bulk-1").addEventListener("change",function(){this.form.querySelectorAll("details").forEach(r=>{if(r.querySelector("[data-article-select]").checked && this.value)r.querySelector("select").value=this.value})});document.getElementById("bulk-2").addEventListener("input",function(){this.form.querySelectorAll("details").forEach(r=>{if(r.querySelector("[data-article-select]").checked && this.value)r.querySelector("input[data-category]").value=this.value})});</script>';page('文章管理',$body);
