<?php
$sid=(int)adminSelectedSite()['id'];$s=query('SELECT * FROM mvp_sites WHERE id=?',[$sid])->fetch();if(!$s)fail('站点不存在');
$published=(int)query('SELECT COUNT(*) FROM mvp_articles WHERE site_id=? AND status="published"',[$sid])->fetchColumn();$drafts=(int)query('SELECT COUNT(*) FROM mvp_articles WHERE site_id=? AND status="draft"',[$sid])->fetchColumn();
$excluded=in_array($sid,[1,2],true)?(int)query('SELECT COUNT(*) FROM mvp_articles WHERE site_id=? AND id=?',[$sid,$sid])->fetchColumn():0;
$file=ROOT.'/.local/benchmark-200/progress.json';$report=$sid===2&&is_file($file)?json_decode(file_get_contents($file),true):null;
$has200Goal=in_array($sid,[1,2,9,10],true);
$effective=in_array($sid,[9,10],true)?$published:$published+$drafts-$excluded;
$goalNote=in_array($sid,[9,10],true)?'目标累计发布200篇，额外生成稿件单独保留。':($has200Goal?'目标200篇，有效数量不包含初始示例。':'内容总量与本次批量任务分别统计。');
$body=adminNav().'<section class="panel"><h1>'.h($s['name']).' · 内容进度</h1><p class="notice">只读进度，不调用模型。'.h($goalNote).'生成文章保存为草稿，发布请在人工文章后台操作；模型意见保留供阅读修改。</p><div class="stats"><div><span>已发布</span><strong>'.$published.'</strong></div><div><span>草稿（含保留内容）</span><strong>'.$drafts.'</strong></div><div><span>'.(in_array($sid,[9,10],true)?'目标发布进度':($has200Goal?'目标进度（不含初始示例）':'当前内容总量')).'</span><strong>'.$effective.($has200Goal?' / 200':'').'</strong></div></div><p><a href="/admin/progress?site_id='.$sid.'">刷新进度</a> · <a href="/admin/articles?site_id='.$sid.'">阅读与修改草稿</a></p>';
if($has200Goal)$body.='<p>'.(in_array($sid,[9,10],true)?'累计已发布 ':'有效内容 ').$effective.' / 200</p><progress max="200" value="'.$effective.'"></progress>';
if($sid===10 && is_file(ROOT.'/.local/chongqing-200/progress.json')){$batch=json_decode(file_get_contents(ROOT.'/.local/chongqing-200/progress.json'),true);$catalogFile=ROOT.'/.local/chongqing-200/catalog.json';$ids=is_file($catalogFile)?array_column(json_decode(file_get_contents($catalogFile),true)['items'],'id'):[];$done=0;foreach(query('SELECT m.metadata FROM mvp_article_meta m JOIN mvp_articles a ON a.id=m.article_id WHERE a.site_id=10') as $row){$meta=json_decode($row['metadata'],true);if(in_array($meta['catalog_id']??'',$ids,true))$done++;}$body.='<section class="notice"><h2>山城怪谈200篇 · '.h($batch['status']).'</h2><p>本批由站长授权 AI 脚本执行：先生成草稿并审核，再统一本地发布与打包；日常修改使用人工后台。</p><p>目录 '.(int)($batch['catalog_count']??0).' / 200；本次新增 '.$done.' / 200；累计已发布 '.$published.' / 200；额外新稿保留为草稿。</p><progress max="200" value="'.$published.'"></progress><p><a href="/admin/catalog?site_id=10">查看选题目录</a> · <a href="/admin/static?site_id=10">查看静态包</a></p></section>';if($batch['status']!=='完成')$body.='<script nonce="'.h(CSP_NONCE).'">setTimeout(()=>location.reload(),30000);</script>';}
else if($sid===9 && is_file(ROOT.'/.local/shanghai-200/progress.json')){$batch=json_decode(file_get_contents(ROOT.'/.local/shanghai-200/progress.json'),true);$catalogFile=ROOT.'/.local/shanghai-200/catalog.json';$ids=is_file($catalogFile)?array_column(json_decode(file_get_contents($catalogFile),true)['items'],'id'):[];$done=0;foreach(query('SELECT m.metadata FROM mvp_article_meta m JOIN mvp_articles a ON a.id=m.article_id WHERE a.site_id=9') as $row){$meta=json_decode($row['metadata'],true);if(in_array($meta['catalog_id']??'',$ids,true))$done++;}$body.='<section class="notice"><h2>沪上异闻200篇 · '.h($batch['status']).'</h2><p>本批由站长授权 AI 脚本执行：先生成草稿并审核，再统一本地发布与打包；日常修改使用人工后台。</p><p>目录 '.(int)($batch['catalog_count']??0).' / 200；本次新增 '.$done.' / 200；累计已发布 '.$published.' / 200；额外新稿保留为草稿。</p><progress max="200" value="'.$published.'"></progress><p><a href="/admin/catalog?site_id=9">查看选题目录</a> · <a href="/admin/static?site_id=9">查看静态包</a></p></section>';if($batch['status']!=='完成')$body.='<script nonce="'.h(CSP_NONCE).'">setTimeout(()=>location.reload(),30000);</script>';}
else if($sid===8 && is_file(ROOT.'/.local/beijing-210/progress.json')){$batch=json_decode(file_get_contents(ROOT.'/.local/beijing-210/progress.json'),true);$catalogFile=ROOT.'/.local/beijing-210/catalog.json';$ids=is_file($catalogFile)?array_column(json_decode(file_get_contents($catalogFile),true)['items'],'id'):[];$done=0;foreach(query('SELECT m.metadata FROM mvp_article_meta m JOIN mvp_articles a ON a.id=m.article_id WHERE a.site_id=8') as $row){$meta=json_decode($row['metadata'],true);if(in_array($meta['catalog_id']??'',$ids,true))$done++;}$body.='<section class="notice"><h2>京城夜谈累计210篇 · '.h($batch['status']).'</h2><p>目录 '.(int)($batch['catalog_count']??0).' / 150；本次新增 '.$done.' / 150；有效目标 '.(60+$done).' / 210（旧试写草稿不计入）。</p><progress max="210" value="'.(60+$done).'"></progress><p><a href="/admin/catalog?site_id=8">查看选题目录</a></p></section>';if($batch['status']!=='完成')$body.='<script nonce="'.h(CSP_NONCE).'">setTimeout(()=>location.reload(),30000);</script>';}
else if($sid===8){$batchFile=ROOT.'/.local/beijing-places-50/progress.json';if(is_file($batchFile)){$batch=json_decode(file_get_contents($batchFile),true);$catalog=json_decode(file_get_contents(ROOT.'/.local/beijing-places-50/catalog.json'),true);$ids=array_column($catalog['items'],'id');$done=0;foreach(query('SELECT m.metadata FROM mvp_article_meta m JOIN mvp_articles a ON a.id=m.article_id WHERE a.site_id=8') as $row){$meta=json_decode($row['metadata'],true);if(in_array($meta['catalog_id']??'',$ids,true))$done++;}$body.='<section class="notice"><h2>北京地名背景50篇 · '.h($batch['status']).'</h2><p>本次新增 '.$done.' / 50 篇；地铁、胡同、小区、公园、大学各10篇，已有首批10篇另行保留。</p><progress max="50" value="'.$done.'"></progress><p><a href="/admin/catalog?site_id=8">查看先行选题目录</a></p></section>';if($batch['status']!=='完成')$body.='<script nonce="'.h(CSP_NONCE).'">setTimeout(()=>location.reload(),30000);</script>';}}
if($sid===1){$loreFile=ROOT.'/.local/lore-200/progress.json';if(is_file($loreFile)){$lore=json_decode(file_get_contents($loreFile),true);$body.='<section class="notice"><h2>城市拾遗200篇 · '.h($lore['status']).'</h2><p>每篇采用独立来源选题，生成后保存草稿。可用独立选题 '.(int)($lore['usable_topics']??$lore['sources_ready']??0).'；实时有效文章 '.($published+$drafts-$excluded).' / 200。</p></section>';if(isset($lore['actual_total_tokens']))$body.='<p>实测耗时 '.round(($lore['seconds']??0)/60,1).' 分钟，实际 '.number_format($lore['actual_total_tokens']).' tokens；'.(int)($lore['model_review_flags']??0).' 篇保留审核提示。</p>';if($lore['status']!=='完成')$body.='<script nonce="'.h(CSP_NONCE).'">setTimeout(()=>location.reload(),30000);</script>';}}
$bulkFile=ROOT.'/.local/complete-200/progress.json';$bulk=$sid===2&&is_file($bulkFile)?json_decode(file_get_contents($bulkFile),true):null;
if($bulk){$body.='<section class="notice"><h2>剩余166篇扩充 · '.h($bulk['status']).'</h2><p>实时有效内容 '.($published+$drafts-$excluded).' / 200；已完成批次 '.count(array_filter($bulk['batches'],fn($b)=>$b['status']==='完成')).'。站长已授权默认通过，全部生成后发布并打包。</p>';if(!empty($bulk['release']))$body.='<p><a href="/admin/static?site_id=2">下载200篇静态包</a></p>';$body.='</section>';if($bulk['status']!=='完成')$body.='<script nonce="'.h(CSP_NONCE).'">setTimeout(()=>location.reload(),30000);</script>';}
$totalTokens=0;$seconds=0;$count=0;
if($report){foreach($report['batches'] as $b){$body.='<section class="panel"><h2>'.$b['size'].'篇试跑 · '.h($b['status']).'</h2><p>开始：'.h($b['started_at']).'</p>';
 if(isset($b['wall_seconds'])){$body.='<p>完整流程 '.round($b['wall_seconds']/60,2).' 分钟；其中目录 '.$b['catalog_seconds'].' 秒、正文与审核 '.$b['article_seconds'].' 秒。实际 '.number_format($b['total_tokens']).' tokens（输入 '.$b['input_tokens'].'，输出 '.$b['output_tokens'].'）。</p>';$totalTokens+=$b['total_tokens'];$seconds+=$b['wall_seconds'];$count+=count($b['articles']);foreach($b['articles'] as $a)$body.='<p><a href="/admin/article/preview?id='.$a['id'].'">'.h($a['title']).'</a> · '.h($a['provider']).' · '.h(empty($a['review']['issues'])?'模型审核通过':'需人工复核').'</p>';}
 else { $partial=ROOT.'/.local/benchmark-200/batch-'.(int)$b['size'].'.json';$done=0;if(is_file($partial)){$topics=array_column(json_decode(file_get_contents($partial),true)['items'],'id');foreach(query('SELECT m.metadata FROM mvp_article_meta m JOIN mvp_articles a ON a.id=m.article_id WHERE a.site_id=?',[$sid]) as $row){$meta=json_decode($row['metadata'],true);if(in_array($meta['catalog_id']??'',$topics,true))$done++;}}$body.='<p>已生成 '.$done.' / '.$b['size'].' 篇；本批已运行 '.max(0,time()-strtotime($b['started_at'])).' 秒。未完成时不显示最终计时和用量。</p>'; }
 $body.='</section>';}}
if($count){$remaining=max(0,200-($published+$drafts-$excluded));$body.='<section class="notice"><h2>按前两批串行样本估算</h2><p>平均每篇 '.number_format($totalTokens/$count).' tokens、'.round($seconds/$count,1).' 秒。还需约 '.$remaining.' 篇（初始示例草稿不计目标），约 '.number_format($remaining*$totalTokens/$count).' tokens、'.round($remaining*$seconds/$count/3600,2).' 小时。</p><p>这是城市背景原创虚构、800—1200字、串行执行的生成估算，包含目录、写作、审核；不含人工审稿、补充来源、发布和上传。真实趣闻额外需要事实提取，不能直接套用同一速度。</p></section>';}
if($report && count(array_filter($report['batches'],fn($b)=>$b['status']!=='完成')))$body.='<script nonce="'.h(CSP_NONCE).'">setTimeout(()=>location.reload(),30000);</script>';
$body.='</section>';page('内容进度',$body);
