<?php
declare(strict_types=1);
function promotionSites(): array { return query('SELECT id,name,base_url,host FROM mvp_sites WHERE id IN (1,2,8,9,10) ORDER BY FIELD(id,1,2,8,9,10)')->fetchAll(); }
function promotionDefaults(): array { return ['title'=>'城市有故事，夜色有回声','intro'=>'在街巷里拾起趣闻，在夜色中听见另一座城。五个故事入口，选一个开始阅读。','footer'=>'城市掌故与原创怪谈 · 总有一个故事，留给好奇的你。','site_ids'=>[1,2,8,9,10]]; }
function promotionConfig(): array { $p=ROOT.'/.local/promotion/config.json'; return is_file($p)?array_replace(promotionDefaults(),json_decode(file_get_contents($p),true,512,JSON_THROW_ON_ERROR)):promotionDefaults(); }
function promotionHtml(array $config, array $sites): string {
    $details=[1=>['CITY JOURNAL','城市掌故 · 日常发现','从熟悉的地名出发，找回城市里被忽略的细节与故事。','拾'],2=>['STREET STORIES','街巷趣闻 · 好奇心入口','转进一条街，遇见一个意想不到的故事。把日常里的有趣，讲给你听。','巷'],8=>['BEIJING AFTER DARK','北京地名 · 原创鬼怪故事','地铁末班、胡同深处、公园夜路。熟悉的北京，是这些虚构怪谈的背景。','京'],9=>['SHANGHAI WHISPERS','上海地名 · 原创恐怖故事','弄堂里的脚步，江边的灯影。用上海的生活质感，讲一段虚构的夜间异闻。','沪'],10=>['CHONGQING SHADOWS','重庆地名 · 原创恐怖故事','坡道、轨道、江雾与层叠楼梯。在熟悉的山城背景里，听一场虚构怪谈。','渝']];
    $cards='';$n=0;
    foreach($sites as $s) {
        $id=(int)$s['id'];if(!in_array($id,$config['site_ids'],true))continue;
        $url=(string)$s['base_url'];if(!filter_var($url,FILTER_VALIDATE_URL)||!in_array(parse_url($url,PHP_URL_SCHEME),['https','http'],true))throw new RuntimeException('站点跳转地址须为有效 HTTP/HTTPS 地址');
        $d=$details[$id];$n++;
        $cards.='<a class="card tone-'.$id.'" href="'.h(rtrim($url,'/').'/').'" target="_blank" rel="noopener"><div class="card-top"><span>'.sprintf('%02d',$n).' / '.h($d[0]).'</span><b aria-hidden="true">'.h($d[3]).'</b></div><div><p class="tag">'.h($d[1]).'</p><h2>'.h($s['name']).'</h2><p class="description">'.h($d[2]).'</p></div><div class="card-bottom"><span>进入阅读 <i aria-hidden="true">↗</i></span><small>'.h($s['host']).'</small></div></a>';
    }
    if(!$n)throw new RuntimeException('请至少选择一个站点');
    $title=h($config['title']);$intro=h($config['intro']);$footer=h($config['footer']);
    return <<<HTML
<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{$title}</title><meta name="description" content="{$intro}"><meta name="color-scheme" content="light"><style>
*{box-sizing:border-box}body{margin:0;background:#f3f0e8;color:#212d2a;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif}a{color:inherit}main{max-width:1180px;margin:auto;padding:36px 28px 60px}.masthead{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #c9cfc6;padding-bottom:22px;font-size:12px;letter-spacing:2px}.brand{font-weight:750;font-size:18px;letter-spacing:3px}.hero{padding:72px 0 56px;max-width:850px}.eyebrow{font-size:12px;letter-spacing:3px;color:#647569}.hero h1{font-family:Georgia,"Songti SC","SimSun",serif;font-weight:600;font-size:clamp(36px,5.5vw,65px);line-height:1.25;letter-spacing:-1px;margin:23px 0}.intro{font-size:17px;line-height:1.9;color:#61716a;max-width:670px}.section-title{display:flex;justify-content:space-between;align-items:center;padding:0 0 20px;font-size:13px;color:#61716a}.grid{display:grid;grid-template-columns:repeat(6,1fr);gap:20px}.card{grid-column:span 2;min-height:335px;padding:27px;display:flex;flex-direction:column;justify-content:space-between;text-decoration:none;border:1px solid #d1d7cf;border-radius:4px;background:#fffdf7;transition:transform .2s,box-shadow .2s}.card:nth-child(1),.card:nth-child(2){grid-column:span 3}.card:hover{transform:translateY(-4px);box-shadow:0 12px 30px #23352e12}.card:focus-visible{outline:3px solid #ae7435;outline-offset:5px}.card-top{display:flex;justify-content:space-between;align-items:center;gap:8px}.card-top span{font-size:10px;letter-spacing:1.3px}.card-top b{font:32px Georgia,"Songti SC",serif;opacity:.5}.tag{font-size:11px;letter-spacing:1px;opacity:.7;margin-top:28px}h2{font:600 30px Georgia,"Songti SC","SimSun",serif;margin:12px 0}.description{font-size:14px;line-height:1.85;opacity:.8}.card-bottom{border-top:1px solid #74857b45;padding-top:18px;margin-top:22px}.card-bottom span{display:flex;justify-content:space-between;font-size:14px;font-weight:600}.card-bottom small{display:block;margin-top:10px;font-size:10px;overflow-wrap:anywhere;opacity:.65}.tone-8{background:#293c3d;color:#f3f0e8;border-color:#293c3d}.tone-9{background:#383449;color:#f3f0e8;border-color:#383449}.tone-10{background:#493b35;color:#f3f0e8;border-color:#493b35}footer{border-top:1px solid #c9cfc6;margin-top:48px;padding-top:24px;color:#647569;font-size:12px;line-height:1.9}footer p{margin:4px 0}@media(max-width:850px){.card,.card:nth-child(1),.card:nth-child(2){grid-column:span 3}}@media(max-width:560px){main{padding:24px 20px 40px}.masthead>span{display:none}.hero{padding:46px 0 32px}.intro{font-size:15px}.grid{grid-template-columns:1fr;gap:16px}.card,.card:nth-child(1),.card:nth-child(2){grid-column:span 1;min-height:310px}.section-title{font-size:11px}footer{margin-top:32px}}
</style></head><body><main><header class="masthead"><a class="brand" href="#stories" style="text-decoration:none">城市故事集</a><span>TAKE A WALK INTO A STORY</span></header><section class="hero"><p class="eyebrow">每一座城，都有另一个入口</p><h1>{$title}</h1><p class="intro">{$intro}</p></section><div class="section-title" id="stories"><span>选择你的故事入口</span><span>{$n} 个故事站点 / 独立阅读</span></div><section class="grid" aria-label="故事站点">{$cards}</section><footer><p>{$footer}</p><p>鬼怪与恐怖故事为原创虚构；真实地名仅作故事背景。点击站点，在新窗口继续阅读。</p></footer></main></body></html>
HTML;
}
function promotionSave(array $config): void {
    $html=promotionHtml($config,promotionSites());$dir=ROOT.'/.local/promotion';if(!is_dir($dir))mkdir($dir,0700,true);
    foreach(['config.json'=>json_encode($config,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT),'index.html'=>$html] as $name=>$content){$tmp=tempnam($dir,'build-');file_put_contents($tmp,$content);chmod($tmp,0600);rename($tmp,$dir.'/'.$name);}
}
